development:
  adapter: mysql
  database: garrick_firstcrackpodcast_wordpress
  username: root
  password: 
  host: localhost

test: &TEST
  adapter: mysql
  database: root_wordpress
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: garrick_firstcrackpodcast_wordpress
  username: 
  password: 
  host: localhost

cucumber:
  <<: *TEST